import * as Dom from './utils/dom';
declare class Player {
    uid: number;
    wrapId: string;
    options: any;
    browser: string;
    event: any;
    loading: boolean;
    loadingTimer: any;
    isFullscreen: boolean;
    el: any;
    mountedNode: any;
    video: any;
    input: any;
    mask: any;
    control: any;
    closeLoading: () => void;
    addEventListener: (type: any, listener: any) => void;
    on: (type: any, listener: any) => void;
    addListener: (type: any, listener: any) => void;
    removeEventListener: (type: any, listener: any) => void;
    off: (type: any, listener: any) => void;
    removeListener: (type: any, listener: any) => void;
    getListener: (type: any) => void;
    trigger: (...args: any[]) => void;
    destory: () => void;
    constructor(id: any, options: any);
    createEl: typeof Dom.createEl;
    init(): void;
    validate(): void;
    isHlsSupported(): void;
    renderVideo(): void;
    renderUnsupport(): void;
    renderError(): void;
    renderToast(): void;
    renderLoading(): () => void;
    unLoading(): void;
    subscription(): void;
}
export default Player;
