export default {
    title:'公共',
    routes:[
        {
            key:'Button',
            title:'按钮'
        },
        {
            key:'Dropdown',
            title:'下拉菜单'
        },
        {
            key:'Alert',
            title:'警告提示'
        },
        {
            key:'Carousel',
            title:'轮播'
        },
        {
            key:'Trigger',
            title:'触发器'
        },
        {
            key:'Tag',
            title:'标签'
        },
        {
            key:'MiniHeader',
            title:'业务头部'
        }
    ]
};