export default {
    title:'通用',
    routes:[
        {
            key:'Button',
            title:'按钮'
        },
        {
            key:'Dropdown',
            title:'下拉菜单'
        },
        {
            key:'Alert',
            title:'警告提示'
        },
        {
            key:'Carousel',
            title:'轮播'
        },
        {
            key:'Trigger',
            title:'触发器'
        },
        {
            key:'Tag',
            title:'标签'
        },
        {
            key:'Select',
            title:'选择器'
        }
    ]
};