export default [
    require('./introduction.md'),
    require('./input-basic.md'),
    require('./input-size.md'),
    require('./input-disabled.md'),
    require('./input-withIcon.md'),
    // require('./input-withTag.md'),
    require('./textarea-basic.md'),
    require('./textarea-maxLength.md'),
    require('./textarea-autoSize.md'),
    require('./input-number.md'),
    require('./input-number-row.md'),
    require('./input-number-withIcon.md'),
    require('./search-basic.md'),
    require('./input-api.md'),
    require('./input-number-api.md'),
    require('./textarea-api.md'),
    require('./search-api.md'),
];